spring.application.name=demo
server.port=8080

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=Test
info.app.description=Test
info.app.version=1.0.0

spring.datasource.db1.jdbc-url=${MYSQL_DB_LOCAL_URL}/${MYSQL_DB_LOCAL_NAME}
spring.datasource.db1.username=${MYSQL_DB_LOCAL_USERNAME}
spring.datasource.db1.password=${MYSQL_DB_LOCAL_PASSWORD}
spring.datasource.db1.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.db2.jdbc-url=${MYSQL_DB_71_URL}/${MYSQL_DB_71_NAME}
spring.datasource.db2.username=${MYSQL_DB_71_USERNAME}
spring.datasource.db2.password=Sbb67@GH8#98%&N35fDev
spring.datasource.db2.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database=default
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update



