spring.application.name=demo

spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/sbicloud_master_20231112
spring.datasource.username=root
spring.datasource.password=1123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.db2.jdbc-url=jdbc:mysql://10.42.53.71:3306/sbicloud_master_03_07_2024
spring.datasource.db2.username=sbiclouddev
spring.datasource.db2.password=Sbb67@GH8#98%&N35fDev
spring.datasource.db2.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database=default



